FROM python:3.10-slim

# Install dependency sistem yang dibutuhkan OpenCV
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements dan install library Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh file aplikasi
COPY . .

# Expose Port 8000
EXPOSE 8000

# Jalankan server Uvicorn / FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]